### PR TITLE
Add the full form data to my submission for Wagtail

### PR DESCRIPTION
**Pull request by thibaudcolas**
Builds upon #169, by adding the full form data I was intending to submit. I kept running into unclear form validation / processing issues, so removed most my submission’s contents but kept a copy.

---

Our full report in Markdown/HTML is available at [wagtail.org/accessibility/atag-audit/](https://wagtail.org/accessibility/atag-audit/).

Our full report in the ATAG Report Tool format is available at [as a GitHub Gist](https://gist.github.com/thibaudcolas/c48b0b4cf8e7966cd09d22677ab63173), as well as my draft submissions to the Authoring Tools list forms.

---

Thank you to the Wagtail accessibility team for the foundational work that made this audit and report possible. It’s a big deal for us that we finally have this first audit, so THANK YOU @Scotchester @thibaudcolas @jessemenn @kbayliss @Stormheg @SaptakS @anujaraj @janehughes @albinazs @laymonage @jams2. Also thank you to my employer Torchbox for sponsoring this audit and associated reporting.

Additional thanks to @albinazs, @jams2, @laymonage, @thibaudcolas, and @nicklee for their work on Wagtail’s first ever accessibility checker (https://wagtail.org/blog/introducing-wagtails-new-accessibility-checker/), which was essential for us to (partly) meet B.3. and B.4. guidelines.

And finally thanks to people who provided early guidance on conducting ATAG audits in the [web-a11y Slack](https://github.com/accessibility/a11yslack) in the #atag channel! This has been an invaluable source of information for us to figure out how to go about this.

### CODE REVIEW

**Comment by thibaudcolas** [comment]
@iadawn @shawna-slh 👋 I see someone is assigned to work on this – is there anything you need from me? Could you give us a heads’up on what to expect with getting this reviewed and merged?

For now this is the information we have from the [submission form](https://www.w3.org/WAI/tools-list/authoring/submit-a-tool/):

> We invite you to use this form to submit your authoring tool to the list. When you submit the form, the data is publicly available in GitHub. We will process it and add it to the list or contact you — usually within 2 weeks. If you have any questions, please send them to: group-wai-list-authoring-tools@w3.org

**Comment by shawna-slh** [comment]
@thibaudcolas Apologies for the delay. We will get to this ASAP. @iadawn

**Comment by thibaudcolas** [comment]
@shawna-slh No worries! This isn’t particularly urgent for us, just keen to know what to expect.

**Comment by thibaudcolas** [comment]
hi @shawna-slh @iadawn, could you let me know where this is at / what to expect on getting this merged and published? We’re not in a hurry but I’d appreciate knowing what the process is so I can report back to my stakeholders and teammates accordingly.

**Comment by shawna-slh** [comment]
Hi @iadawn

I merged and published this PR. However, it's not showing up at https://www.w3.org/WAI/tools-list/authoring/

fyi, at the same time, I merged https://github.com/w3c/wai-authoring-tools-list/pull/173 , which is showing up.

**Comment by thibaudcolas** [comment]
@iadawn @shawna-slh would it help if I made an alternative submission that only has "yes/no/partially/not applicable" type information?

I see the Joomla! submission that came through is much simpler than what I proposed. I wanted to provide enough information for people to make an informed evaluation, but I can link to our ATAG report or VPAT instead if the authoring tools list doesn’t work well with descriptions.

**Comment by iadawn** [comment]
@shawna-slh This one was merged into [w3c:form-submission/bb977ce0-7d5a-11ee-8199-edfb8b607e2e-c68ee32](https://github.com/w3c/wai-authoring-tools-list/tree/form-submission/bb977ce0-7d5a-11ee-8199-edfb8b607e2e-c68ee32) not into master. I will sort out a PR from that into master which you should be able to merge and publish.

**Review by dennismuchene — COMMENTED** [review]
wwww.google.com

**Pull request merged**
